fix: Make umc server deployment policy configurable to allow for quicker deployment and scaleup
This field is not editable during an upgrade:
  Error: UPGRADE FAILED: cannot patch "nubus-umc-server" with kind
  StatefulSet: StatefulSet.apps "nubus-u
  mc-server" is invalid: spec: Forbidden: updates to statefulset spec
  for fields other than 'replicas', 'or
      dinals', 'template', 'updateStrategy',
      'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are f
      orbidden

Changing this value requires deleting the statefulset.
For this reason this commit only makes it configurable and does not
change the default value.

univention/dev/internal/team-nubus#1363